# Generated by Django 5.1.7 on 2025-04-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_rename_company_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(default=990, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.position'),
            preserve_default=False,
        ),
    ]
